apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
    spec:
      containers:
        - name: patient-service
          image: python:3.12-slim
          command: ["python", "-m", "http.server", "8001"]
          ports:
            - containerPort: 8001
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"