replicaCount: 1

image:
  repository: notification-service
  tag: local
  pullPolicy: Never

service:
  port: 8004

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

hpa:
  enabled: false

serviceAccount:
  create: false