replicaCount: 1

image:
  repository: patient-service
  tag: local
  pullPolicy: Never       # use locally built minikube image

service:
  port: 8001

databaseSecretName: patient-service-db-secret

env: {}

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

hpa:
  enabled: false          # disable HPA for now (Phase 6)

serviceAccount:
  create: false           # no IRSA needed locally