replicaCount: 1

image:
  repository: patient-service
  tag: local
  pullPolicy: Never

service:
  port: 8001

env:
  databaseSecretName: patient-service-db-secret

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 30   # lower threshold so it's easy to trigger locally

serviceAccount:
  create: false