apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "audit-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "audit-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "audit-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.serviceAccount.roleArn }}
      serviceAccountName: {{ .Release.Name }}
      {{- end }}
      containers:
        - name: audit-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
            {{- if .Values.dynamodbEndpointUrl }}
            # dev only — points boto3 to DynamoDB Local instead of real AWS
            - name: DYNAMODB_ENDPOINT_URL
              value: {{ .Values.dynamodbEndpointUrl | quote }}
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.awsAccessKeyId | quote }}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.awsSecretAccessKey | quote }}
            {{- end }}
            # prod: no DYNAMODB_ENDPOINT_URL — boto3 uses real AWS DynamoDB via IRSA
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: {{ .Values.healthCheck.path }}
              port: {{ .Values.healthCheck.port }}
            initialDelaySeconds: {{ .Values.healthCheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthCheck.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.healthCheck.path }}
              port: {{ .Values.healthCheck.port }}
            initialDelaySeconds: 15
            periodSeconds: 20
